# Generated by Django 5.2.4 on 2025-08-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publucation_year',
            new_name='publication_year',
        ),
    ]
